id: I5B29E808
default_language: bo
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:30:58.979765
last_modified: 2023-01-04 11:30:58.979790
source_metadata:
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
bases:
  '1517':
    title: A Guide to Uḍḍiyāna (Ujjain), Benglor
    base_file: 1517.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
